### ISSUE TITLE
gr-dvbsgse for gnu radio 3.8

### ISSUE THREAD

**Issue by sanjuambiger** [drmpeg/gr-dvbgse#2]
hi all
**does this work with gnu radio 3.8 or is there a separate branch for gnu radio 3.8 ?**
Thank You in advance

**Comment by drmpeg** [comment]
No, but I can port it. Give me a day or two.

**Comment by sanjuambiger** [comment]
Okay ,Thank You

**Comment by drmpeg** [comment]
It's ready.

https://github.com/drmpeg/gr-dvbgse38

**Comment by sanjuambiger** [comment]
thank you so much 
you are the best.
